// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var arr = [
  1,
  2,
  3
];

function func(a, b) {
  return a + b | 0;
}

var x = 10;

var height = 10.0;

var isNull = true;

var name = "ten";

var character = /* "c" */99;

var unitTest;

var opt = 10;

var tuple = [
  10,
  "ten"
];

var l = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

exports.x = x;
exports.height = height;
exports.isNull = isNull;
exports.name = name;
exports.character = character;
exports.unitTest = unitTest;
exports.opt = opt;
exports.tuple = tuple;
exports.l = l;
exports.arr = arr;
exports.func = func;
/* No side effect */
