// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


Math.pow(2.0, 3.0);

var integers = {
  hd: 23,
  tl: {
    hd: -12,
    tl: /* [] */0
  }
};

exports.integers = integers;
/*  Not a pure module */
